steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lengolf-crm', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lengolf-crm']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lengolf-crm'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lengolf-crm'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--no-allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/lengolf-crm'